### ISSUE TITLE
License differs

### ISSUE THREAD

**Issue by Miolus** [CraftMusic-Bot/CraftMusic-OSS#1]
Different licenses are used for the same project.

**Comment by TheDomCraft** [comment]
But we are using the MIT License, because this is the Correctly License for this Project

**Comment by Miolus** [comment]
Can u change it then in the package files?

**Comment by Miolus** [comment]
Cause they show ISC

**Comment by Miolus** [comment]
as license

**Comment by TheDomCraft** [comment]
Yes, i can do it. Thanks
