### ISSUE TITLE
Wo ist Skriptum

### ISSUE THREAD

**Issue by Sound-Cat** [CraftMusic-Bot/CraftMusic-OSS#2]
Sieht ein bisschen aus wie Rythm

**Comment by TheDomCraft** [comment]
Warum denn?

**Comment by TheDomCraft** [comment]
Der bot hat die Basic commands die jeder Musikbot haben muss. Wie willst du ohne play command z.b. Musik abspielen?

Nur weil ein musik bot einen standart command hat den jeder musik bot hat ist es eine unverschämtheit ihn mit anderen , höheren bots zu vergleichen. 

CraftMusic ist legendlich von Rythm inspiriert

**Comment by TheDomCraft** [comment]
Der bot hat nur die Standard commands die wichtig sind das er Funktioniert. Er hat keine extra Features sondern eh nur das aller nötigste. Daher kann man den bot nicht mit Rythm vergleichen.
